# Generated by Django 4.2.7 on 2023-11-03 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0001_initial"),
        ("dash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="registration",
            field=models.OneToOneField(
                default=2002,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_profile",
                to="register.registration",
            ),
            preserve_default=False,
        ),
    ]
