# Generated by Django 4.2.7 on 2023-11-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("age_group", models.CharField(max_length=50)),
                ("doctor", models.CharField(max_length=255)),
                (
                    "last_vaccine_certificate",
                    models.FileField(upload_to="vaccine_certificates/"),
                ),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.CharField(max_length=50)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="register.registration",
                    ),
                ),
            ],
        ),
    ]
