# Generated by Django 4.2.7 on 2023-11-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_name", models.CharField(max_length=255)),
                ("parent_name", models.CharField(max_length=255)),
                ("relationship_to_child", models.CharField(max_length=255)),
                ("child_birthdate", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
