# Generated by Django 4.2.7 on 2023-11-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
